name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@2.1.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
